apiVersion: batch/v1
kind: Job
metadata:
  name: seeder-color-static
spec:
  template:
    metadata:
      name: seeder-color-static
    spec:
      containers:
      - name: seeder-color-static
        image: sogis/docker-mapcache
        command:
        - mapcache_seed
        - -c
        - /mapcache/mapcache.xml
        - -t
        - ch.so.agi.hintergrundkarte_farbig
        - -f
        - -z
        - 0,10
        - -n
        - "2"
        - -d
        - /mapcache/wmts-seeding-perimeter.gpkg
        - -l
        - kanton1000m
        volumeMounts:
        - mountPath: /tiles
          name: mapcache-tiles
      restartPolicy: Never
      volumes:
      - name: mapcache-tiles
        emptyDir: {}
